### ISSUE TITLE
Missing footer

### ISSUE THREAD

**Issue by lucascolusso** [alikolberg/forms#1]
Footers can be found at the bottom of almost every web page.

Users scan or read the page and either don’t find what they want or need more information. They scroll to the bottom of a page and use the footer as:

**A second chance to be convinced**
For example, maybe a user has decided, after reading all the details, that she doesn’t want to sign up for a bank account, but she was still impressed with the banking institution and wants to become a customer. The footer is a good opportunity to remind or teach potential customers about the company’s other offerings.

**A last resort for hard-to-find content**
Sometimes users turn to the footer for additional options that might not be present in the global navigation. For example, those interested in applying for a job with an ecommerce company — a task that is different from those of the typical ecommerce customer—might look to the footer for relevant information.

**Reference**
https://www.nngroup.com/articles/footers/

**Comment by alikolberg** [comment]
Footer added

**Comment by alikolberg** [comment]
information added
